### ISSUE TITLE
Error: Recipe `test` with shebang `#!/usr/bin/env bash` execution error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by Kronk74** [casey/just#1611]
Hello :)

I'm using just to run command on my server and I created a recipe with bash commands like this : 

Justfile
```
test:
  #!/usr/bin/env bash
  echo "This is a test"
```

Error : 
`error: Recipe `test` with shebang `#!/usr/bin/env bash` execution error: Permission denied (os error 13)`

Do I missed something ? Is someone already had this issue ?

I's a fresh new machine in Ubutu 22.04.

Regards,

**Comment by JohnathanFL** [comment]
I just hit the same issue and came to check if somebody had made an issue for it already. The problem (at least in my case) is that I had `/tmp` mounted `noexec`.

Try temporarily doing `sudo mount -o remount,exec /tmp` and see if that fixes anything.

**Comment by casey** [comment]
Thanks for opening this issue! @aidanharris opened #1708, which fixes the issue by using `XDG_CACHE_HOME` if the tmpdir is mounted with noexec. I'm thinking that instead of checking if the tempdir is mounted noexec, we might just consider using `XDG_CACHE_HOME` to avoid the extra dependency on checking mountpoint options. Does anyone have any opinions on this?

**Comment by casey** [comment]
I just merged #2067, which always uses the cache dir if available. We'll see if it causes problems for anyone, if so, we can explorer checking for `noexec`.

**Comment by airtonix** [comment]
fyi, I still have to put this in my `~/.bashrc` in wsl2 or i still get these errors. 


```sh
XDG_RUNTIME_DIR="$(mktemp -d "/tmp/xdg-runtime-XXXXXX")"
XDG_CACHE_HOME="$(mktemp -d "/tmp/xdg-cache-XXXXXX")"
export XDG_CACHE_HOME
export XDG_RUNTIME_DIR
```

**Comment by W1M0R** [comment]
@airtonix If you would prefer not needing to update your `~/.bashrc` file, then you can also consider using the unstable `[script]` attribute with just recipes, instead of shebangs. You might need to add `set unstable` to your justfile for that to work.

**Comment by lucastheisen** [comment]
Im new to just, so sorry if i missed something important.  I was testing around the edges of this issue here (wsl2 running rockylinux 9), it appears its not using `XDG_CACHE_HOME`, instead only using `XDG_RUNTIME_DIR`:

```console
(wsl-rocky9) ltheisen@PC ~
$ XDG_RUNTIME_DIR="${HOME}/tmp" just doit 123
Version: 123

(wsl-rocky9) ltheisen@PC ~
$ XDG_CACHE_HOME="${HOME}/tmp" just doit 123
error: Recipe `doit` with shebang `#!/usr/bin/env bash` execution error: Permission denied (os error 13)
```

And it is quite common to have tmpfs (which run is usually) mounted `noexec`, and mine definitely is:

```console
(wsl-rocky9) ltheisen@PC ~
$ mount | grep "${XDG_RUNTIME_DIR%/}"
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
```

So using `XDG_RUNTIME_DIR` is likely not a good choice.  Could we maybe allow a `--shebang-dir` option, or allow `JUST_SHEBANG_DIR` to be explicit?  or even a `~/.config/just.yml` to provide global defaults or something?

Also there is no mention of this in --help or even the [shebang recipies](https://just.systems/man/en/shebang-recipes.html?highlight=shebang#shebang-recipes) page.

**Comment by casey** [comment]
Check out #2798. I added a `--tempdir` command-line option, which can also be configured with `JUST_TEMPDIR`, which can be used to globally override where shebang and script recipes are written. I also added documentation explaining the different ways the temporary directory can be configured.

**Comment by kenden** [comment]
@casey 

I am getting the following error when using `~`. Maybe the param `--tempdir` should take an absolute path?

```bash
just --tempdir=~/tmp foo
error: Recipe `foo` could not be run because of an IO error while trying to create a temporary directory or write a file to that directory: No such file or directory (os error 2) at path "/home/redacteduser/dev/~/tmp/just-3FlApn"
```

**Comment by lucastheisen** [comment]
@kenden , the `~` is a shell shortcut, but it only works when its the first character of an argument.  If you switch from using `=` to using space, it should work:

```console
ltheisen@MY-PC ~
$ echo --tempdir=~/tmp
--tempdir=~/tmp

ltheisen@MY-PC ~
$ echo --tempdir ~/tmp
--tempdir /home/ltheisen/tmp
```

So use:

```bash
just --tempdir ~/tmp foo
```

**Comment by kenden** [comment]
@lucastheisen Thanks, I didn't know that. It does work with a space:
```bash
$ just --tempdir ~/tmp foo  #fine
$ just --tempdir=$HOME/tmp foo  #fine
$ just --tempdir=~/tmp foo  #breaks
```
