### ISSUE TITLE
Release job failed for linux/arm64 at 1.25.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [casey/just#1941]
https://github.com/casey/just/actions/runs/8196561542/job/22417043127

```
  error occurred: Failed to find tool. Is `aarch64-linux-musl-gcc` installed?
```

https://github.com/casey/just/releases/tag/1.25.0

<img width="455" alt="image" src="https://github.com/casey/just/assets/13323303/7fd724c5-deb1-47ee-abd4-f6b8e8caec63">

Some pre-built binaries weren't released.

**Comment by casey** [comment]
Fixed! I think this was caused by the new blake3 dependencies, but installing some inscrutable packages and exporting some inscrutable environment variables fixed it. Prebuilt binaries are available on the [release page](https://github.com/casey/just/releases/tag/1.25.0).

**Comment by suzuki-shunsuke** [comment]
Release still failed at 1.25.1.

https://github.com/casey/just/releases/tag/1.25.1

<img width="448" alt="image" src="https://github.com/casey/just/assets/13323303/ccaf4ed5-7cfa-4fb8-87b1-e649d159d6f7">

https://github.com/casey/just/actions/runs/8217664170/job/22473612069

```
error[E0425]: cannot find value `MAP_32BIT` in crate `libc`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.11.1/src/sys/mman.rs:53:9
   |
53 |         MAP_32BIT;
   |         ^^^^^^^^^ not found in `libc`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `nix` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

<img width="338" alt="image" src="https://github.com/casey/just/assets/13323303/aa149c34-3024-46c3-91da-f941dcfad514">

**Comment by suzuki-shunsuke** [comment]
I opened a new issue because the error message was different.

- https://github.com/casey/just/issues/1949
