### ISSUE TITLE
just --list --unsorted deals with imports in reverse order.

### ISSUE THREAD

**Issue by gl-yziquel** [casey/just#2076]
Hi.

Just noticed the following: whereas `just --list --unsorted` lists the recipes in the order in which they are defined in the Justfile, it lists the recipes in the imported Justfiles in the **reverse** order in which the Justfiles are imported.

This is hugely counterintuitive.

**Comment by casey** [comment]
Fixed in #2085. Thank you for the report!

**Comment by gl-yziquel** [comment]
You're most welcome. Now, I'll have to reverse all my imports...

**Comment by gl-yziquel** [comment]
Hmmmh. I just built 1.27.0 (which is where I see the puported fix in the git history). And I still see the buggy behaviour.

`Justfile`:

```just
import "task1.just"
import "task2.just"

[private]
@help:
    just --list --unsorted --justfile "{{ justfile() }}"
```
`task1.just`:
```just
task1:
    echo Task 1
````
`task2.just`:
```just
task2:
    echo Task 2
```

When running `just`, I get:

```console
Available recipes:
    task2
    task1
```

Wrong ordering.

I don't see it fixed.

**Comment by casey** [comment]
Sigh, I fixed it for modules, not imports 😅

**Comment by casey** [comment]
Fixed in #2092!

**Comment by gl-yziquel** [comment]
Yes. Much better. However, if you allow me to be a pain, here is another related behaviour, which I'm not sure will be most easy to address:

`Justfile`:
```just
import "task1.just"
import "task2.just"

[private]
@help:
    just --list --unsorted --justfile "{{ justfile() }}"

task3:
    echo Task 3
```

That will render as follows:
```console
Available recipes:
    task3
    task1
    task2
```

Not sure how easy that behaviour will be to fix. Should I open another issue ?

**Comment by casey** [comment]
Hmmm, the current behavior is that recipes in the current module are printed first, then recipes from imports, which are printed first by the order of the import in the top file, and then in the order they appear in the import.

I can see the argument for printing them, in the case of your example, in `task1 task2 task3` order. Why don't you open an issue and we can get some user feedback?

**Comment by gl-yziquel** [comment]
OK.

Discussion ? Or issue ?

I assume discussion.

Here: https://github.com/casey/just/discussions/2095

**Comment by gl-yziquel** [comment]
@casey Wow !! Modules are pretty impressive !! Thank you so much !!
